# Default values for servicechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: message-server
  tag: 0.0.1
  pullPolicy: IfNotPresent

metaconfig:

# Service level configs
extraconfig: # List service level config

# Make this true only if you have extrasecrets, the data of which is managed seperately by authorize personnel
extrasecrets: false

extraingress:
  enabled: true
  name: messages
  prefix: /messages/
  service: messages
  port: 4000
  grpc: false

# metaegressrules:
# extraegressrules:

servicehttp:
  type: ClusterIP
  port: 4000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  minreplicas: 1
  maxreplicas: 1
  cpuavgpercent: 70
  memavgvalue: 200Mi

deployment:
  minreadyseconds: 5